# Generated by Django 6.0.6 on 2026-06-19 03:12

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0003_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('peso', models.DecimalField(decimal_places=2, help_text='Porcentaje de la evaluacion.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10)),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.periodoacademico')),
            ],
            options={
                'verbose_name': 'evaluacion',
                'verbose_name_plural': 'evaluaciones',
                'ordering': ['materia', 'periodo', 'nombre'],
                'constraints': [models.CheckConstraint(condition=models.Q(('peso__gt', 0)), name='evaluacion_peso_mayor_que_cero')],
            },
        ),
    ]
