# Generated by Django 6.0.6 on 2026-06-19 03:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_matricula'),
        ('notas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=4, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('20.00'))])),
                ('observacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('evaluacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='notas.evaluacion')),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.matricula')),
            ],
            options={
                'verbose_name': 'nota',
                'verbose_name_plural': 'notas',
                'ordering': ['-fecha_registro'],
                'constraints': [models.UniqueConstraint(fields=('matricula', 'evaluacion'), name='nota_unica_por_matricula_evaluacion'), models.CheckConstraint(condition=models.Q(('calificacion__gte', 0), ('calificacion__lte', 20)), name='nota_calificacion_entre_0_y_20')],
            },
        ),
    ]
