# Generated by Django 6.0.6 on 2026-06-20 21:33

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0004_alter_materia_codigo'),
        ('notas', '0002_nota'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='evaluacion',
            name='evaluacion_peso_mayor_que_cero',
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='peso',
            field=models.DecimalField(decimal_places=2, help_text='Porcentaje de la evaluacion.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('1.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AddConstraint(
            model_name='evaluacion',
            constraint=models.CheckConstraint(condition=models.Q(('peso__gte', 1), ('peso__lte', 100)), name='evaluacion_peso_entre_1_y_100'),
        ),
        migrations.AddConstraint(
            model_name='evaluacion',
            constraint=models.UniqueConstraint(fields=('materia', 'periodo', 'nombre'), name='evaluacion_unica_por_materia_periodo_nombre'),
        ),
    ]
