# Generated by Django 6.0.6 on 2026-06-19 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0002_periodoacademico'),
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_matricula', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('matriculado', 'Matriculado'), ('retirado', 'Retirado'), ('finalizado', 'Finalizado')], default='matriculado', max_length=12)),
                ('estudiante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='estudiantes.estudiante')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.materia')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.periodoacademico')),
            ],
            options={
                'verbose_name': 'matricula',
                'verbose_name_plural': 'matriculas',
                'ordering': ['-fecha_matricula'],
                'constraints': [models.UniqueConstraint(fields=('estudiante', 'materia', 'periodo'), name='matricula_unica_por_estudiante_materia_periodo')],
            },
        ),
    ]
