# Generated by Django 6.0.6 on 2026-06-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academico', '0003_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='codigo',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
