# Generated by Django 6.0.6 on 2026-06-19 04:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academico', '0003_matricula'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('presente', 'Presente'), ('tardanza', 'Tardanza'), ('falta', 'Falta'), ('justificado', 'Justificado')], default='presente', max_length=11)),
                ('observacion', models.TextField(blank=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('matricula', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academico.matricula')),
            ],
            options={
                'verbose_name': 'asistencia',
                'verbose_name_plural': 'asistencias',
                'ordering': ['-fecha', 'matricula'],
                'constraints': [models.UniqueConstraint(fields=('matricula', 'fecha'), name='asistencia_unica_por_matricula_fecha')],
            },
        ),
    ]
