# Generated by Django 6.0.6 on 2026-06-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='codigo',
            field=models.CharField(editable=False, max_length=20, unique=True),
        ),
    ]
